using Nest;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace HT_Design_Pattern.PageObjects
{
    public class InboxPage : BasePage
    {
        public InboxPage() : base("")
        {
        }

        //TODO long and autogenerated xpath
        public IWebElement CommposeBoxField => WebDriver.GetInstance().FindElement(By.XPath("//div[@jscontroller='eIu7Db']"));
        
        public WebDriverWait wait = new WebDriverWait(WebDriver.GetInstance(), TimeSpan.FromSeconds(30));
        public IWebElement SenderMailField => WebDriver.GetInstance().FindElement(By.CssSelector("input[role=combobox]"));
        public IWebElement SubjectField => WebDriver.GetInstance().FindElement(By.Name("subjectbox"));
        public IWebElement TextBoxField => WebDriver.GetInstance().FindElement(By.XPath("//div[@aria-label='Message Body']"));
        public IWebElement SaveCloseField => WebDriver.GetInstance().FindElement(By.XPath("//img[@alt='Close']"));


        public void Compose(string senderMail, string subject, string textbox)
        {
            wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(CommposeBoxField));
            var CommposeBox = new Button(CommposeBoxField);
            CommposeBox.Click();
            wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(SenderMailField));
            SenderMailField.SendKeys(senderMail); 
            SubjectField.SendKeys(subject); 
            TextBoxField.SendKeys(textbox); 

            var SaveCloseButton = new Button(SaveCloseField);
            SaveCloseButton.Click();
        }



    }
}
